### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by ghost** [levelhq/level#162]
![image](https://user-images.githubusercontent.com/33036105/97918283-a80f1e00-1d34-11eb-84f4-6cba4d2110b3.png)
Hello, how are you/
I think your tool is something my team could use so I tried to deploy it to heroku (to check how it works first) and it was pretty smooth, but when going and trying to create an user I get this error.
Do you happen to know waht can it be?
Thanks

**Comment by derrickreimer** [comment]
Hey @santiagoworkana, I'm afraid I'm unable to provide support for this codebase (it's no longer under active maintenance).

It's worth checking out [Twist](https://twist.com/) by the Todoist team for a similar communication tool!
