### ISSUE TITLE
Command line version of the SVG to Elm converter

### ISSUE THREAD

**Issue by jtakacs** [levelhq/level#163]
Can you please extract the code that does the SVG -> Elm conversion into a command line tool, so I can use it locally without compiling & running the rest of the Level app?

**Comment by derrickreimer** [comment]
Hi @jtakacs, I don't have the bandwidth at the moment to maintain that, but you can grab the relevant code here: https://github.com/unstacked/level/blob/master/lib/level/svg.ex
