### ISSUE TITLE
Ability to join a space by sharing a URL

### ISSUE THREAD

**Issue by derrickreimer** [levelhq/level#41]
During guided setup, the plan is to present the user with a "magic link" that can be shared around with colleagues (dare I say, posted in Slack?) to quickly join a space.

## To Do

- [ ] Create an `open_invitations` table to store the token and state
  - These can be "revoked" by the space owner at any time
- [ ] Add an `allow_open_invitations` boolean to `spaces`, non-nullable, default to `true`
  - When `false`, then signing up via an open invitation should be disallowed
- [ ] Auto-generate an open invitation when the space is created

**Comment by hugo** [comment]
Hey, @derrickreimer. This seems like a good first issue. I’d like to work on it if that’s okay with you?

**Comment by derrickreimer** [comment]
Hey @hugo! This one is a sort of entangled with some of the new auth logic that I'm working on in a series of branches. I think I'll probably knock this out as a part of the onboarding work that I'm doing right now. Thanks for asking -- I plan to file some issues soon that would be good candidates for the community to work on.
