### ISSUE TITLE
Gracefully redirect from GraphiQL when not logged in

### ISSUE THREAD

**Issue by derrickreimer** [levelhq/level#83]
Right now, it just errors out hard:

![image](https://user-images.githubusercontent.com/341387/40944049-f1ab206e-6818-11e8-9db3-07957738dd61.png)

## Repro Steps

- Load the server
- Make sure no user is logged-in
- Visit http://localhost:4000/graphiql

## Acceptance Criteria

In this scenario, redirect the user to the sign-in page. Controller tests appreciated.

**Comment by sleepiejohn** [comment]
I'll take a go at it, if no one is already working on it 😸

**Comment by derrickreimer** [comment]
Go for it!

**Comment by sleepiejohn** [comment]
Done, it was simple as add a already present plug into the pipeline. 😊

**Comment by sleepiejohn** [comment]
omg I probably was sleeping to let that pass 😅 , thanks for pointing it out, fixed!
