### ISSUE TITLE
Contributing guidelines?

### ISSUE THREAD

**Issue by codyduval** [levelhq/level#98]
Would it be useful to have a _short_ markdown document that outlines how one can contribute?  Perusing the backlog and issues, it wasn't clear to me what sort of help is needed at this point in Level's lifecycle.  A "way in" to the project could help focus folks who are interested in helping but not sure on where to start.

Here are a few examples from similar product-as-open-source type projects:
[Discourse Contributing Guidelines](https://github.com/discourse/discourse/blob/master/CONTRIBUTING.md)
[Ghost Contributing Guide](https://docs.ghost.org/v1/docs/contributing#section-submitting-pull-requests)

Finally, if it's not covered under the Apache License it may also be worth asking contributors to agree to some sort of [Contributor License](https://docs.ghost.org/v1/docs/contributing#section-contributor-license-agreement).

Thanks, and keep up the great work @derrickreimer!

**Comment by derrickreimer** [comment]
Thanks! For now, I've refined the README to reflect the current state of community contributions: https://github.com/levelhq/level/blob/master/README.md#project-status

**Comment by IanVS** [comment]
From the readme, it sounds like contributions are not yet welcome, since you're working on this alone for now.  Is that a correct interpretation?

**Comment by derrickreimer** [comment]
Correct. And to be clear, it's purely a practical concern to keep the roadmap as tight as possible on the journey to launch.
